### ISSUE TITLE
GroveGesture notificationExec VOLUME_UP/VOLUME_DOWN not working as expected

### ISSUE THREAD

**Issue by lxne** [eouia/MMM-Volume#11]
Hi,
I installed the module-fork for the Seeed Respeaker 2-Mics hat on my Pi 3b+ (buster) and in general it works fine, but I stumbled across some issues with MMM-GroveGesture.

For example, when I try to do a VOLUME_UP with GroveGesture like this:
```
        "CLOCKWISE": {
          notificationExec: {
            notification: "VOLUME_UP",
            payload: null,
          }
        },
```
it won't work. The gesture is being recognized but the volume does not change.
If I change the payload to `0` it uses the default upDownScale value and works.
And payload `{upDownScale: 10}` is working too (volume changes by 10).

But `payload: null,` should work too? Am I right?

**Comment by eouia** [comment]
It should have worked, but last PR merging seems lost that feature. I'll patch it in some time. Sorry for inconvenience.

**Comment by eouia** [comment]
Patched. Update and try to test it again.
```js
.sendNotification("VOLUME_DOWN")
```
or
```js
.sendNotification("VOLUME_DOWN", null)
```
will work.

**Comment by lxne** [comment]
Thank you very much.
Now it works as expected.
And thanks for including the code for Respeaker 2-Mics hat!
