### ISSUE TITLE
Volume is not changed by the module (Command failed: amixer sset -M 'PCM')

### ISSUE THREAD

**Issue by sergge1** [eouia/MMM-Volume#13]
I am running MagicMirror:latest+MMM-Volume on my Raspberry Pi (detailed environment below). 
Raspberry outputs sound through card 1: usb c-media sound card (see `aplay -l` results in the env section below)

MMM-Volume does not change the system volume. 

I have put in config to decrease the volume to 4%, it retursn with an error in terminal log: 

```
[2020-02-05 21:54:49.891] [LOG]    [VOLUME] Set Volume Error: Error: Command failed: amixer sset -M 'PCM' 4%
amixer: Unable to find simple control 'PCM',0


    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:200:13)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:200:13)
    at Pipe.<anonymous> (net.js:586:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: "amixer sset -M 'PCM' 4%"
```

<details><summary>Extract from config.js</summary>
<p>

```
{
	module: "MMM-Volume",
	disabled: false,
	position: "top_left", // It is meaningless. but you should set.
	config: {
		usePresetScript: "ALSA", // "ALSA" is supported by default.
		volumeOnStart: 4,
	}
},
```
</details> </p>

<details><summary>**Environment:**</summary>
<p>

>Raspbian version
```
pi@raspberrypi:~/MagicMirror $ cat /etc/os-release
>PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
>NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

>Linux core
```
pi@raspberrypi:~/MagicMirror $ uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```
>Hardware model
```
pi@raspberrypi:~/MagicMirror $ cat /proc/device-tree/model
Raspberry Pi 3 Model B Plus Rev 1.3
```
>Node and NPM version

`pi@raspberrypi:~ $ node -v
v10.18.1`
`pi@raspberrypi:~ $ npm -v
6.13.4`

>Audio devices
```
pi@raspberrypi:~/MagicMirror $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Device_1 [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
</details> </p>

> **Before you post issue, try this first**
> - Confirm you have completed installation with instruction
> **Confirmed**
> - Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
> **Confirmed**
> - If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.
> **Confirmed. PM2 is not used**

**Comment by eouia** [comment]
Maybe your ALSA setup doesn't have `PCM`. 
Try this on your terminal shell.
```
amixer sset -M 'Master' 10%
```
If volume is changed, configure your config.js like this;
```js
usePresetScript: null,
getVolumeScript: `amixer sget 'Master' | awk -F"[][]" '{print ""$2""}' | grep %  | awk '{gsub ( /%/, "" ) ; print}'`, 
setVolumeScript: `amixer sset -M 'Master' #VOLUME#%`, 
```

Everybody might have a different environment, so if `presetScript` doesn't work, find proper command for your environment and use it.

**Comment by sergge1** [comment]
Thank you for quick responses 
Will check today

**Comment by sergge1** [comment]
amixer sset returns the following
```
pi@raspberrypi:~ $ amixer sset -M 'Master' 100%
amixer: Unable to find simple control 'Master',0
```
will look for other options

**Comment by eouia** [comment]
Sorry. I don't know your environment. You need to find a proper command to control your RPI volume by yourself.

**Comment by sergge1** [comment]
I have found this one - this commands  10%+ increases and 10%- decreases by voulme by 10% (percentage could be any)
```
pi@raspberrypi:~ $ amixer set Speaker 10%+
Simple mixer control 'Speaker',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 151
  Mono:
  Front Left: Playback 68 [45%] [-15.63dB] [on]
  Front Right: Playback 68 [45%] [-15.63dB] [on]
pi@raspberrypi:~ $ amixer set Speaker 30%+
Simple mixer control 'Speaker',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 151
  Mono:
  Front Left: Playback 114 [75%] [-7.00dB] [on]
  Front Right: Playback 114 [75%] [-7.00dB] [on]
```

**Comment by sergge1** [comment]
>  your environment

i have clean Buster updated/upgraded. RPi 3 B+. usb sound card

**Comment by eouia** [comment]
So, try this;
```js
usePresetScript: null,
getVolumeScript: `amixer sget Speaker | awk -F"[][]" '{print ""$2""}' | grep %  | awk '{gsub ( /%/, "" ) ; print}'`, 
setVolumeScript: `amixer sset -M Speaker #VOLUME#%`, 
```

**Comment by sergge1** [comment]
> So, try this;
> 

Thank you. 
Can't check the volume change right now, only volume set at the start. 
But during the start the module is set to the level specified in config. 
Also, dark-blue rectangle disappear as needed (from #14 )
Will install telegram later and will check the volume change and report here.

**Comment by sergge1** [comment]
> will check the volume change and report here.

Checked. New command works well with RPi & Buster. Thanks. Will add pull request to add this config to readme.md
