### ISSUE TITLE
Visual appearance -  static dark blue block at the main MagicMirror's screen

### ISSUE THREAD

**Issue by sergge1** [eouia/MMM-Volume#14]
When running MMM-Volume, I am getting the static dark blue block on my main MagicMirror's screen - see the screenshot https://github.com/sergge1/bugs/blob/master/MMM-Volume/volume.png
May be this relates to my previous issues #13 

<details><summary>Extract from config.js</summary>
<p>

```
{
	module: "MMM-Volume",
	disabled: false,
	position: "top_left", // It is meaningless. but you should set.
	config: {
		usePresetScript: "ALSA", // "ALSA" is supported by default.
		volumeOnStart: 4,
	}
},
```
</details> </p>

<details><summary>**Environment:**</summary>
<p>

>Raspbian version
```
pi@raspberrypi:~/MagicMirror $ cat /etc/os-release
>PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
>NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

>Linux core
```
pi@raspberrypi:~/MagicMirror $ uname -a
Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```
>Hardware model
```
pi@raspberrypi:~/MagicMirror $ cat /proc/device-tree/model
Raspberry Pi 3 Model B Plus Rev 1.3
```
>Node and NPM version

`pi@raspberrypi:~ $ node -v
v10.18.1`
`pi@raspberrypi:~ $ npm -v
6.13.4`

>Audio devices
```
pi@raspberrypi:~/MagicMirror $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Device_1 [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
</details> </p>

> **Before you post issue, try this first**
> - Confirm you have completed installation with instruction
> **Confirmed**
> - Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
> **Confirmed**
> - If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.
> **Confirmed. PM2 is not used**

**Comment by eouia** [comment]
It has the same cause with issue #13, so I'll close this.
