### ISSUE TITLE
GET_VOLUME Notification

### ISSUE THREAD

**Issue by Ejay-3D** [eouia/MMM-Volume#2]
Hi Sean , 

I'm trying to achieve the following using Volume Module and notification trigger volume : 

~~~~
triggers: [
          {
            trigger: "ASSISTANT_RESPONSE_END", // HOTWORD_LISTENING if you use MMM-HOTWORD  or HOTWORD_RESUME if you use MMM-AssistantMk2
            fires: [
              {
                fire: "standby_Image",
                payload: payload => {
                  var img = document.getElementById("MY_ANIMATION");
                  img.src = "modules/MMM-AI/jarvis-standby2.gif";
                  return payload;
                }
              }
            ]
          },
		   {
            trigger: "HOTWORD_SLEEPING", // HOTWORD_SLEEPING if you use MMM-HOTWORD  or HOTWORD_RESUME if you use MMM-AssistantMk2
            fires: [
              {
                fire: "VOLUME_GET",
				 exec: "amixer sset -M 'PCM' 10%"
              }
			 
            ]

          },
	{
            trigger: "ASSISTANT_UNDERSTOOD", // HOTWORD_SLEEPING if you use MMM-HOTWORD  or HOTWORD_PAUSE if you use MMM-AssistantMk2
            fires: [
              {
                fire: "VOLUME_RESTORE",
                payload: payload => {
                  var img = document.getElementById("MY_ANIMATION");
                  img.src = "modules/MMM-AI/jarvis-talk2.gif";
                  return payload;
                }
              }
            ]
          }
        ]
      }
    },
~~~~

Workflow is like : 
Standby -> User hotword -> trigger notification "HOTWORD_SLEEPING" -> **Get current Volume** by  fire: "VOLUME_GET" ( that is where i'm failing ) -> set volume to 10 with the exec ( that works ok -> trigger "ASSISTANT_UNDERSTOOD" -> fire "VOLUME_RESTORE" to restore volume from the previous GET Etc .... 

So Far the volume is reduce ok in the right workflow place . But I'm unable to set it back with VOLUME_RESTORE from the previous VOLUME_GET call . 

I think i'm not getting how this is working or I might miss some param ? 

thanks for your help . 

Ejay

**Comment by eouia** [comment]
I think;
Trigger : ASSISTANT_ACTIVATE
Fire : VOLUME_STORE with payload volume to change temporary

Trigger : ASSISTANT_UNDERSTOOD
Fire : VOLUME_RESTORE

You don't need to get current volume by yourself. VOLUME_STORE will be save current value and change to new volume, and VOLUME_RESTORE will restore previous saved volume.

**Comment by eouia** [comment]
But frankly said, I didn't test it yet. You are my Guinea pig to test. :D

**Comment by Ejay-3D** [comment]
Just had to change : fire: "VOLUME_GET",   to fire: "VOLUME_STORE", 
And All works ! 

Thanks
