### ISSUE TITLE
Notification with MMM-AssistantMk2

### ISSUE THREAD

**Issue by ReoLusia** [eouia/MMM-Volume#9]
I want to control volume states with MMM-AssistantMk2 module.

Can I use MMM-Volume notification just with MMM-AssistantMk2?

It's hard to understand the function code of volume control.

**Comment by Tom-Hirschberger** [comment]
The module works with the notifications described in the readme. It does not matter which other module is sending them. VOLUME_UP,  VOLUME_DOWN,...

**Comment by ReoLusia** [comment]
It works with notification in case of VOLUME_GET.
But in cases of VOLUME_UP and VOLUME_DOWN, response like this...

[AMK2] Volume control... Not yet supported

**Comment by eouia** [comment]
That's not an issue of MMM-Volume.
Your transcriptionHook might be using reserved words(intents) of Google Assistant itself. Sorry, that is a side-effect limitation of transcriptionHooking. use gAction for natural voice command  to avoide pre-defined default Google Action instead transcriptionHook.
Or you can use other phrase instead "volume", Maybe it could be "louder"... (not tested)

**Comment by eouia** [comment]
If you have no other further issue, I'll close this. Have a good luck.
